name: tekartik_midi_device_alsa_linux
description: Midi device on linux
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:

  tekartik_midi_device:
    git:
      url: https://github.com/tekartikprj/midi_device
      path: packages/midi_device
  tekartik_alsa_midi_linux:
    git:
      url: https://github.com/tekartikprj/midi_device
      path: packages/alsa_midi_linux
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_app_rx:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_rx
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
